server:
  port: 10061 # Port choisi pour Eureka (évite les plages réservées Windows)

spring:
  application:
    name: service-discovery

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false